name: Docker Image CI

on:
  push:
    paths:
      - '**' # 包含所有文件
      - '!README.md' # 排除特定文件
      - '!.gitignore' # 排除特定文件
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Docker Metadata action
      uses: docker/metadata-action@v4.4.0
      id: meta
      with:
       images: sxk485/gemini2chatgpt
       tags: latest

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
       context: .
       push: true
       labels: ${{ steps.meta.outputs.labels }}
       tags: ${{ steps.meta.outputs.tags }}
